language: scala

scala:
- 2.12.6
- 2.11.12
- 2.13.0-M4

jdk:
- oraclejdk8

cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt"

script:
  - if [[ "${TRAVIS_PULL_REQUEST}" == "false" &&
          "${TRAVIS_BRANCH}" == "master" &&
          $(cat version.sbt) =~ "-SNAPSHOT"
    ]]; then
      travis_wait 50 sbt ++${TRAVIS_SCALA_VERSION} validate publish ;
    else
      travis_wait 50 sbt ++${TRAVIS_SCALA_VERSION} validate ;
    fi

sudo: false

notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/7d9188983e70fdb9839f

env:
  global:
  - secure: ltfR5hReS8UiUMkB6c1gMEBWI47E+Hg56p9dnYfP3GEq+Xht2EKKAZR8myoOd3B2gYEACUl/E9rhbNDYpvobAi44cAmwPxA0Gwdj0Bp4XiOHiEWh1zPgTRTHrntgeR9jmB2IxfhRXjurf4LNFY/ehhP48BeOywdb0CO4idchaY2AMvUjmWV35Cy7vqPbOWqLUgGzwa8tVxJ5BJhL2Orz18AqC22iixheHXrGLTHU/HtbSVXfA6D8Xt1qR9gOeRzZQ5XPcv4RS/aj5Bexn83fp0kovUeEcpu6xCA+gMrPL27cQ1FD+CsN53ldQTxSnd7HXDRORxDJnoZxbsFjArfP11KI5KRZ+Witt1+ImZmT4/Cjxr4nOROLEvY1CP1Jj8jgqvu7ysJF6vwBRrNPAPKi5d72eQQNs5JMhwzTDNd2+9WJNydbSzfztq8OVjKgKGVGgHSbjkin0eguIGj9uhJZEg68zz39Cj/GUjIGd87eFo5N01T0UEMf/Jgcq0ezXPArrocsPaxxc7DR2mRQ/DFpqPhFE/tmr9mueRkywvSQbQO6kG4KUPfuNzTc303lLBkgwcarm6hTCbxrci8DaegMKG+V5+8+Cr+jxtkDyAGT9bVzEy/zS4zLLpfHNORZqRljJPj3DCT8iJHyVJ/SBOnp/DQyJnNkTN0oG8HkYgqDR3Y=
  - secure: DwC01G1CHtg/yfUCCvzyB7suqckui8WgxTKDT/V51hOUGVGBDFF+zqBXe8VqPh03Qp3ZN88AcESBsvthA7b+x1GvMdDy78jYQ6jLMdfWli3VrcVkjM8JMgpbN9EyfSQTyGeXKuFhvqY8MKhoHiKcFK4jfZpiDACZkv3CsOX0M5P8q9zgYw3mNiNvC/QwZ6NIYPNsq+2wWQtOyz5HpGbEtJbe8yRC82vpMn3BDBLjAJcxJI3gbTnKLFZ+sd92IIdBHKGjfUFDf/o+xuPfbqyFWtQxeAtLHobOn+tQbKXA6LdC1IEyG89L9MpV3A5VAkOV/C1840fL7Igmg0xqmk8z87lz3goCafXQFcp1wjpbf5uIZ76kqOgYMnX0BV/mTu2P4gOCnnA4Xhr9Q4ua2QzJy9Vh+DkWZU4rwprFK9A4SsmUied0EOki5VF5+WdPrQGSAxbTrBDr4GjbwHBUcJWZOi1QmlAW8XntGhWJax7FcCe3MTBMtSMb46q2NXYsnOulJV+7Vq/HYG0rJYD2L8SgZJ7qHsZOygJiGdMO4nJi8v749gkpEXiciM3dahteTe+w0W8aaTTi2aT0j06RmSp0XV5R6vJqu+MWtRtb6Z4s9G8/5SdeEuh/5Tfb9CniSX85kHrcXFonFzH0E4cR7V5+Ml1KNtDfMOkmA887wfxytv0=
