addSbtPlugin("com.github.gseitz"                 % "sbt-release"            % "1.0.10")
addSbtPlugin("com.jsuereth"                      % "sbt-pgp"                % "1.0.1")
addSbtPlugin("com.typesafe.sbt"                  % "sbt-git"                % "0.9.3")
addSbtPlugin("org.scala-js"                      % "sbt-scalajs"            % "0.6.24")
addSbtPlugin("org.xerial.sbt"                    % "sbt-sonatype"           % "1.1"  )
addSbtPlugin("com.thoughtworks.sbt-api-mappings" % "sbt-api-mappings"       % "0.2.2")
addSbtPlugin("org.portable-scala"                % "sbt-scalajs-crossproject" % "0.6.0")
